# generated by zon2nix (https://github.com/nix-community/zon2nix)
{
  linkFarm,
  fetchzip,
  fetchgit,
}:
linkFarm "zig-packages" [
  {
    name = "axe-0.7.0-M2JU5ceNAAAsFTeUNNISXldu4sg-3yT3zEBc1-ObTb9W";
    path = fetchgit {
      url = "https://github.com/ratakor/axe";
      rev = "ee0b7f46fee3988844c06bc66038477c8aa86d8d";
      hash = "sha256-tUx3rcGeWxkO3L8wIEzK8SfxH44FS3ZE7vPPsMUWDLU=";
    };
  }
  {
    name = "clap-0.11.0-oBajB-HnAQDPCKYzwF7rO3qDFwRcD39Q0DALlTSz5H7e";
    path = fetchzip {
      url = "https://github.com/Hejsil/zig-clap/archive/refs/tags/0.11.0.tar.gz";
      hash = "sha256-XytqwtoE0xaR43YustgK68sAQPVfC0Dt+uCs8UTfkbU=";
    };
  }
  {
    name = "sizeify-0.0.0-URVFj1EhAAAXtotBNFwEx5W70ygRnAdHjBYcg4F_CahM";
    path = fetchgit {
      url = "https://github.com/ciathefed/sizeify";
      rev = "0ef93d13a44f231f392c4804ed3b724b3031b8d0";
      hash = "sha256-uvuaho/QhNMtvf+8xTb1Peg6e7zje2JijcmGbQwyjLM=";
    };
  }
  {
    name = "zeit-0.6.0-5I6bk0J9AgCVa0nnyL0lNY9Xa9F68hHq-ZarhuXNV-Jb";
    path = fetchgit {
      url = "https://github.com/rockorager/zeit";
      rev = "ed2ca60db118414bda2b12df2039e33bad3b0b88";
      hash = "sha256-IvXaqAzaWi3E1XBqQltCBFoRmXehZkVol3/RZwOsAKg=";
      # url = "https://github.com/rockorager/zeit?ref=zig-0.15";
      # hash = "sha256-oG9Z3Y9Cgvlw9DwmDK99TwdU19L1irLE0bhq6tKOfI8=";
    };
  }
]
