# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "axe-0.8.0-M2JU5SuRAABRUbICFInh_GltUm46JBd986HQCE7j6BJz";
    path = fetchgit {
      url = "https://github.com/Ratakor/axe";
      rev = "186078c497e4e4dab20926c1b135fa9ab8a6a3b1";
      hash = "sha256-DV4yH43OBzmeLTRZXRWVn8r+TEI22u4bmhdr4nLg+4U=";
    };
  }
  {
    name = "clap-0.11.0-oBajB7foAQC3Iyn4IVCkUdYaOVVng5IZkSncySTjNig1";
    path = fetchgit {
      url = "https://github.com/Hejsil/zig-clap";
      rev = "fc1e5cc3f6d9d3001112385ee6256d694e959d2f";
      hash = "sha256-sIDCZW4q9BQwy4AJjJ6r+mSkJ3usbnMmY9zkE4EVAy8=";
    };
  }
  {
    name = "sizeify-0.0.0-URVFj1EhAAAXtotBNFwEx5W70ygRnAdHjBYcg4F_CahM";
    path = fetchgit {
      url = "https://github.com/ciathefed/sizeify";
      rev = "0ef93d13a44f231f392c4804ed3b724b3031b8d0";
      hash = "sha256-uvuaho/QhNMtvf+8xTb1Peg6e7zje2JijcmGbQwyjLM=";
    };
  }
  {
    name = "zeit-0.6.0-5I6bk7q6AgBdMJxze3D4l9ylQhkviQ_BX9FigDt13MFn";
    path = fetchgit {
      url = "https://github.com/rockorager/zeit";
      rev = "2a79678e05e4e82cd4efd4fd6b754dcf029c3a64";
      hash = "sha256-LFNg8yu82OcQ+Yyxw1bTotjW18oVhNiYrFGIE/7WWR4=";
    };
  }
]
